import type { Metadata } from 'next';
import './globals.css';
import { Navbar } from '@/components';
import { UserProvider } from '@auth0/nextjs-auth0/client';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=David+Libre:wght@400;500;700&family=Frank+Ruhl+Libre:wght@300..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <UserProvider>
        <body>
          <Navbar />
          <main>{children}</main>
        </body>
      </UserProvider>
    </html>
  );
}
